0 silly input [ 'test' ]
1 silly flags { _: [ 'run' ],
1 silly flags   'reject-cycles': false,
1 silly flags   rejectCycles: false,
1 silly flags   script: 'test',
1 silly flags   args: [] }
2 verbose rootPath /Users/gpr08/Github/blaze
3 info version 2.11.0
4 silly existsSync /Users/gpr08/Github/blaze/VERSION
5 info versioning independent
6 silly initialize attempt
7 silly initialize success
8 silly execute attempt
9 silly runScriptInDir test [] atoms
10 silly getExecOpts { cwd: '/Users/gpr08/Github/blaze/packages/atoms' }
11 error test Errored while running script in 'blaze-atoms'
12 error execute callback with error
13 error Error: Command failed: yarn run test
13 error error An unexpected error occurred: "Command failed.
13 error Exit code: 1
13 error Command: sh
13 error Arguments: -c jest --no-cache
13 error Directory: /Users/gpr08/Github/blaze/packages/atoms
13 error Output:
13 error ".
13 error yarn run v1.5.1
13 error $ jest --no-cache
13 error No tests found
13 error In /Users/gpr08/Github/blaze/packages/atoms
13 error   218 files checked.
13 error   testMatch: **/__tests__/**/*.js?(x),**/?(*.)+(spec|test).js?(x) - 0 matches
13 error   testPathIgnorePatterns: /node_modules/ - 218 matches
13 error Pattern:  - 0 matches
13 error info If you think this is a bug, please open a bug report with the information provided in "/Users/gpr08/Github/blaze/packages/atoms/yarn-error.log".
13 error info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
13 error
13 error     at Promise.all.then.arr (/Users/gpr08/Github/blaze/node_modules/lerna/node_modules/execa/index.js:236:11)
13 error     at <anonymous>
